### ISSUE TITLE
What about Vue 3 support?

### ISSUE THREAD

**Issue by eladcandroid** [f5/unovis#152]

**Comment by rokotyan** [comment]
There's no official Vue integration as of now. However you can still use Unovis with Vue because the core of the library is written in TypeScript.

We're accepting contributions, if you want to help us create a Vue integration, let us know!

**Comment by errantmind** [comment]
I'm using Unovis with Vue3 and plain javascript and it works fine. I mostly referenced the Typescript docs and then mentally translated that to javascript where necessary. There were a few gotchas to get it to re-render properly when Vue state changes, but it is doable. Let me know if you run into any issues here @eladcandroid  and I'll try to help.

**Comment by zernonia** [comment]
Hey @rokotyan ! Im the maintainer for [Shadcn Vue](https://github.com/radix-vue/shadcn-vue), and I would love to contribute to this Vue3 integration. Could you assign this to me? 😁

**Comment by rokotyan** [comment]
@zernonia That's awesome! Can you send me a note to nikita@f5.com? I would like to discuss the process with you over a call if you're open to that.

**Comment by rokotyan** [comment]
The Vue 3 integration has been merged into the main branch 🥳 Kudos to @zernonia for this amazing contribution!

It'll be officially announced with the 1.3.0 release, but you you want to use it already, use version `1.3.0-beta.3`: https://www.npmjs.com/package/@unovis/vue/v/1.3.0-beta.3
