### ISSUE TITLE
Link source and target attributes randomly switch between being a string and a node object.

### ISSUE THREAD

**Issue by ndtreviv** [f5/unovis#190]
When my graph renders, the link source and target attributes are strings:
<img width="751" alt="image" src="https://user-images.githubusercontent.com/1530653/234624164-064c64fc-47f1-444c-8f21-f9a464fa7b8f.png">

But then at some point they get changed into node objects instead:
<img width="744" alt="image" src="https://user-images.githubusercontent.com/1530653/234624346-a89be9ef-927a-40fb-8d07-e1fef463c04f.png">

I'm not editing these links in any way as far as I can tell.

**Comment by rokotyan** [comment]
Confirming the issue. Will be solved in `1.1.1`
