### ISSUE TITLE
Actual numTicks > data.length ?

### ISSUE THREAD

**Issue by pietz** [f5/unovis#201]
I really like the behavior that `numTicks` is not exactly bound to the final value. However, recently I'm fighting with an error, which I believe comes from the fact that the actual (final) number of ticks is larger than the length of my data array. This happens with named (string based) bars.

Is this possible? I'm having a bit of trouble debugging the issue.

**Comment by reb-dev** [comment]
Hi @pietz, thanks for posting! You might be better off explicitly setting the tick values with the axis property `tickValues`, as `numTicks` is only meant to be an approximation.

If that doesn't help, feel free to share your code or a Stackblitz example so I can better understand the exact problem you're facing.

**Comment by pietz** [comment]
That's what I did to solve my problem. The point above still stands though. Setting `numTicks` to `n` might also result in `>n` values, which then leads to out of bounds errors. I'm not convinced this is a reasonable behavior.

I close the issue for now.
