### ISSUE TITLE
Svelte v4 Support

### ISSUE THREAD

**Issue by pheuter** [f5/unovis#236]
[Svelte v4](https://github.com/sveltejs/svelte/releases/tag/svelte%404.0.0-next.0) is coming, would be nice to be able continue using `@unovis/svelte`.

**Comment by rokotyan** [comment]
Thanks for the heads up @pheuter!

We've added Svelte 4 to the peer dependencies list in #237 and I plan to release it along with Unovis v1.2 within the next few days. The Svelte 4 integration hasn't been tested yet, so we'd appreciate it if you could report any problems you encounter.

**Comment by rokotyan** [comment]
Unovis 1.2 with preliminary Svelte 4 support just got released
