### ISSUE TITLE
Force Graph is refusing to accept height constant, stays at 300px default.

### ISSUE THREAD

**Issue by TheBitmonkey** [f5/unovis#247]
Great Repo,

I cannot seem to get a Single Container to accept the height I would like. I am working with svelte. 

<VisSingleContainer {data} height={'60vh'}> this line does not work. 

The documentation says const height = 100 but does not explain how to get that const into the single container. Is this a versioning issue or some change. 

Any help would be greatly appreciated. Cheers.

**Comment by rokotyan** [comment]
@TheBitmonkey Can you please share an example that reproduces the issue via StackBlitz or any other online code editor?

**Comment by TheBitmonkey** [comment]
Well that seem completely fair. Let me get back to you on that.

**Comment by TheBitmonkey** [comment]
OK, it works as described on Stackblitz. I needed to force install the svelte peer dependency though which I didn't need to do locally. Maybe the issue is there. I will continue on.

Thanks.

**Comment by rokotyan** [comment]
@TheBitmonkey Great, I'm glad to hear it's working. That's interesting about the svelte peer dependency, we'll keep an eye on it. If you come across any more issues or have further questions, feel free to reach out.
