### ISSUE TITLE
Hidden tooltip overflows viewport

### ISSUE THREAD

**Issue by Coronon** [f5/unovis#286]
I am currently implementing quite a long `VisTooltip` on a `VisXYContainer`. I wrap the content of this tooltip using CSS, which works as expected. Sadly, when the tooltip was first shown on a larger screen and the viewport is resized to be smaller, the CSS `left` property on the tooltip container does not update which causes the viewport to overflow horizontally. As soon as the user hovers my chart again and the `left` value is recomputed+updated, this overflow goes away.

As a quick fix I propose to use `display: none` to hide the tooltip when it is not shown instead of `opacity: 0`. Another solution would be allowing people to overwrite the styles of the container itself instead of only it's content.

Version: `1.2.1(@unovis/ts@1.2.1)(svelte@4.2.1)`

**Comment by rokotyan** [comment]
@Coronon Nice catch, it was bothering me as well.

@reb-dev Can you please look into this? If we simply use `display: none` we won't have smooth fade outs, but maybe we can come up with some trick that will make it work.

**Comment by rokotyan** [comment]
@Coronon We've just released version `1.2.3` containing this fix
