### ISSUE TITLE
Getting empty graphs when x values are strings

### ISSUE THREAD

**Issue by kwarc-star** [f5/unovis#305]
I am getting empty graphs whenever my x values are string. Tried with stacked line and stacked bar charts. They work fine if the values are number/date. Am I missing anything?

```
<VisBulletLegend items={legendItems} />
  <VisXYContainer data={chartData} height={"50vh"}>
  <VisTooltip triggers={triggers} />
  <VisGroupedBar
    x={useCallback((d) => d.x, [])}
    y={headers.map((header) =>
      useCallback((d) => d[header.name], [])
    )}
  />
</VisXYContainer>
```

When d.x outputs number or date, it works fine.

**Comment by rokotyan** [comment]
@kwarc-star Bar charts in Unovis don't support string values. If you want to create an ordinal bar chart, you can refer to this section from our documentation: https://unovis.dev/docs/guides/tips-and-tricks/#displaying-ordinal-values

**Comment by deekshithmr95** [comment]
can you provide the working stackblitz example?
