### ISSUE TITLE
Graph: Using SVGs as node icons

### ISSUE THREAD

**Issue by rokotyan** [f5/unovis#319]
That would be great to be able to use SVGs as node icons. Currently only icon fonts are supported.

**Comment by Arro** [comment]
+1 for this!

**Comment by rokotyan** [comment]
@Arro If you're interested in trying out this feature, you can use version `1.4.0-alpha.9`. Here's usage example: https://github.com/rokotyan/unovis/commit/a47e83a5b18a26579d019cbf6bf22390d4812ea6.
