### ISSUE TITLE
[Svelte]: custom colours are never applied to crosshair points through the `VisCrosshair` component

### ISSUE THREAD

**Issue by shyakadavis** [f5/unovis#338]
Hi;

Following the specification here in the docs: https://unovis.dev/docs/auxiliary/Crosshair#custom-color, I tried providing my custom colours to the `VisCrosshair` component, but they are never applied.

Something like this:

```svelte
<VisCrosshair template={tooltip_template} color={generate_crosshair_points_colours} />
```

where the `generate_crosshair_points_colours` function is simply this:

```ts
export function generate_crosshair_points_colours<T>(_: T, i: number) {
	return ['hsl(var(--primary))', 'hsl(var(--primary) / 0.25)'][i];
}
```

Though, simple colours like ['red', 'green'] like specified in the docs reference above seem to work. It only fails, I think, for such CSS variable values like the ones I'm using.

While I have you, do you know of a way to programmatically specify the `circle-stroke-color` & `circle-stroke-width` like we are doing for the colours themselves?

Thanks.

**Comment by rokotyan** [comment]
@shyakadavis We'll investigate this and get back to you. 

As for your second question, it might be possible via the undocumented `attributes' config property and custom CSS for the defined attributes. I'll see if I can come up with an example, but it will be tricky to set up. Maybe we should just add it as another config property.

**Comment by shyakadavis** [comment]
Thanks for the reply, @rokotyan 

> We'll investigate this and get back to you.

Thank you for the consideration.

> Maybe we should just add it as another config property.

That would be very helpful. Please do.
