### ISSUE TITLE
Multi-Selection Dragging

### ISSUE THREAD

**Issue by mossy426** [f5/unovis#363]
For large datasets especially in molecular epidemeology, it's common to want to select groups of nodes that aren't necessarily connected to eachother, as well as then be able to drag all these nodes at once to make the network more legible rather than spending a long time dragging one by one.  

Users can typically do this by doing something such as holding shift + mouse button press and dragging on the network to create a rectangle, and on release - highlight all the nodes within said rectangle.  

Is there any way to select multiple nodes?  Not just highlight nodes that are connected to a selected node.

I see the selectedNodeId variable is used like so:

```
<vis-graph
  [nodeLabel]="nodeLabel" 
  [events]="events" 
  selectedNodeId="2"
></vis-graph>
```

Please see the images below for reference.  Thanks in advance!  Excited to collaborate with eachother :) 

<img width="1670" alt="Rect" src="https://github.com/f5/unovis/assets/80353770/950a9184-a7f2-4e1e-b7ee-a37860a07839">

![selected](https://github.com/f5/unovis/assets/80353770/c5d214ce-ac7e-4a3a-a9e2-84aeb635a5e3)

**Comment by rokotyan** [comment]
@mossy426 That would really be a great feature. We'll keep it in mind for the next component update. I can't give any estimate though on how soon we'll be able to add it.
