### ISSUE TITLE
VisAnnotations not available in @unovis/vue

### ISSUE THREAD

**Issue by mcdaded** [f5/unovis#378]
When importing the `VisAnnotations` module from `@unovis/vue` the module is not available. It seems the module is available in `/components/annotations` but is not imported in the `/components.ts` file.

**Comment by lee00678** [comment]
Hi @mcdaded, you are right! Thanks for bringing this to our attention. We are working on a fix.

**Comment by lee00678** [comment]
@mcdaded we just put out a new release `1.4.1` with a fix for this.
