### ISSUE TITLE
Multiple Issues linked to TopoJSON Maps

### ISSUE THREAD

**Issue by GauthierNelkinsky** [f5/unovis#400]
Hello, I'd like to point out a few issues with the TopoJSON maps: 
- In the [documentation](https://unovis.dev/docs/maps/TopoJSONMap), when you want to navigate on a map, it disappears, leaving only the points visible.
- The feature allowing you to add a TopoJSON Overlay to a map does not work (tested on Vue). It also doesn't work in the [documentation](https://unovis.dev/docs/maps/LeafletMap#topojson-overlay).

**Comment by rokotyan** [comment]
@GauthierNelkinsky Thank for reporting this!  We'll take a look
