### ISSUE TITLE
Make Donut Example Responsive

### ISSUE THREAD

**Issue by curran** [f5/unovis#454]
**User story:**

As a developer working on the responsive behavior of a component, I want to be able to test out both the horizontal and vertical resizing, so that I can implement the correct resize behavior.

**Details:**

While working on #441, I noticed that the Unovis Dev site does not allow you to test the responsive behavior of the donut chart. Horizontal resize works fine, but not vertical. I propose to modify the existing donut chart example to showcase vertical responsiveness.

**Reproduction:**

 * `npm run dev`
 * Navigate to http://localhost:9500/examples/Donut/Donut:%20Empty%20Segments
 * Resize the browser horizontally - observe correct responsive layout
 * Resize the browser vertically - observe that the container remains a fixed height

<img width="1015" alt="image" src="https://github.com/user-attachments/assets/b511e10f-fce6-487d-9ea4-525e12f6e006">

**Comment by curran** [comment]
Blocked by https://github.com/f5/unovis/issues/455

**Comment by 50rayn** [comment]
Is this issue still valid since it was fixed in #455?
