### ISSUE TITLE
`tickTextAlign: 'center'` errors unless `tickTextAngle` is specified

### ISSUE THREAD

**Issue by davestewart** [f5/unovis#470]
We're trying to use `tickTextAlign` but it seems to error unless we set `tickTextAngle` as well:

![CleanShot 2024-10-23 at 09 32 10](https://github.com/user-attachments/assets/1281a3eb-af1d-435a-abf1-07c6577a70fe)

Checking the stack, it appears the variable is undefined (at least) here:

![CleanShot 2024-10-23 at 09 30 59](https://github.com/user-attachments/assets/7a11a562-32ca-4582-bd14-a1d6204fd609)

**Comment by lee00678** [comment]
@davestewart thanks for catching this issue! I've added a fix here: https://github.com/f5/unovis/pull/473
