### ISSUE TITLE
Ref undefined 

### ISSUE THREAD

**Issue by sss1337xyz** [f5/unovis#472]
I use nextjs 

I can’t access the ref because it is always undefined,
you don’t have to go far to find the assembly, it’s in the documentation

url https://unovis.dev/gallery/view/?collection=Maps&title=Advanced%20Leaflet%20Map
![image](https://github.com/user-attachments/assets/ccc758aa-fcd5-4849-a111-fe935b4fe7ad)

**Comment by rokotyan** [comment]
Thanks for reporting @sss1337xyz, we'll take a look
