### ISSUE TITLE
How to detect whether chart is rendered or not?

### ISSUE THREAD

**Issue by fromaline** [f5/unovis#481]
Hey, thanks for this fantastic library!

I’m using it in a Svelte/SvelteKit project and came across a minor issue that I'd appreciate some guidance on. If a user is on a slower internet connection, the charts can take a bit of time to render, even with SSR. I'd like to display a loader until the chart is fully rendered to improve the user experience.

Is there any way to check programmatically whether a chart has finished rendering or if it’s still in the loading/rendering phase?

Thanks for your help, and for the work you do!

**Comment by rokotyan** [comment]
@fromaline Unovis renders the chart in the following frame after data has been passed to the component. If used with Svelte, rendering will likely be delayed by only 1–2 frames.

I believe you can connect your loader to your data-fetching routines rather than the Unovis rendering process.

**Comment by fromaline** [comment]
@rokotyan, got it! Thanks for the clarification! Since I’m using SSR, the data is already baked in from the server, so there’s no additional data-fetching. However, I still need to show a loader for those couple of frames while the chart renders. Is there a way to detect when the rendering is complete?

**Comment by rokotyan** [comment]
@fromaline I'm not sure we understand your problem well. Could you please share your project or at least a video showcasing the problem?

**Comment by fromaline** [comment]
Here’s the page where I’m encountering the issue https://chainspect.app/chain/ethereum?noloader=1
And here’s a video showcasing the problem (exaggerated with throttling for clarity):

https://github.com/user-attachments/assets/6a0be486-08ea-4a25-acaf-631d63a07ae9

The page is server-rendered using SvelteKit, so everything except images is already there, but the chart isn’t rendered yet. That’s why I added a loader. You can see the loader in action without the `noloader` query parameter https://chainspect.app/chain/ethereum

Right now, the loader is implemented using Svelte’s built-in tick function like this:

```javascript
tick().then(() => {
  isChartLoading = false;
});
```
However, I’d prefer to rely on the Unovis library itself to detect when the chart rendering is complete

**Comment by rokotyan** [comment]
@fromaline Thanks, looks like the issue is somehow related to SSR and SvelteKit. Currently, it's out of our bandwidth as we're busy with the 1.5 release, but we're open to contributions!

**Comment by fromaline** [comment]
@rokotyan, got it! Good luck with the new release! I don’t have much time to dig deeper into this issue, so I’ll stick to my current solution.
Thanks again for the great library and for taking the time to respond 🙏🏻
