### ISSUE TITLE
Candlestick shape

### ISSUE THREAD

**Issue by jfilby** [f5/unovis#58]
It would be great to see a candlestick shape included in the library, for financial apps.

**Comment by ralyodio** [comment]
Came here to request this. Nobody has done a professional open source candlestick chart yet.

**Comment by rokotyan** [comment]
@jfilby @ralyodio 
Can you please elaborate why candlestick charts from other libraries didn't work for you?
* TradingView has Lightweight Charts, it's an amazing, hight performance and platform-independent library for all sorts of time series charts and it has the candlestick option: https://www.tradingview.com/lightweight-charts/;
* VisX by Airbnb supports Candlestick as well https://airbnb.io/visx/statsplot;
* Semiotic: https://semiotic.nteract.io/examples/candlestick-chart;
* ...
