### ISSUE TITLE
Uncaught typeerror when using LeafletFlowMap with react

### ISSUE THREAD

**Issue by ereid7** [f5/unovis#75]
Running into the following error when attempting to use LeafletFlowMap with react

![Capture](https://user-images.githubusercontent.com/27597719/208220540-9b1462b8-7c5d-4e7c-b679-ba85fa6a7fe1.PNG)

My Component:
```
const FlightMapComponent = (props) => {
  const style = `https://api.maptiler.com/maps/positron/style.json?key=${key}`
  const attribution = [
    `<a href="https://www.maptiler.com/copyright/" target="_blank">MapTiler</a>`,
    `<a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap contributors</a>`
  ]

  return (
    <VisLeafletFlowMap 
      data={data}
      style={style}
      height={600}
    />
  );
}
```

package.json
```
"dependencies": {
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@unovis/react": "^1.0.0",
    "@unovis/ts": "^1.0.0",
    "bootstrap": "^5.2.3",
    "react": "^18.2.0",
    "react-bootstrap": "^2.7.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.5.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
```

**Comment by ereid7** [comment]
My workaround to fixing this issue is to use optional chaining in `destroy` method of  `ts/src/components/leaflet-flow-map/index.ts`

```
public destroy(): void {
    this.resizeObserver?.disconnect()
    this.renderer?.destroy()
    this.canvasElement?.removeEventListener('mousemove', this.onCanvasMouseMoveBound)
    this.canvasElement?.removeEventListener('click', this.onCanvasClickBound)
    super.destroy()
  }
```

When debugging, `destroy` is called _before_ this block of code executes:
https://github.com/f5/unovis/blob/9544d8e309b23fb318debd9971526b434897850a/packages/ts/src/components/leaflet-flow-map/index.ts#L57

Which is causing the error in my first comment. I will post if I figure out more information

**Comment by rokotyan** [comment]
@ereid7 Unfortunately I'm not able to reproduce the issue. Can you please create a simple example on StackBlitz and share it? You can use this one as a placeholder: https://unovis.dev/gallery/view?collection=Maps&title=Leaflet%20Flow%20Map

**Comment by ereid7** [comment]
@rokotyan Here is a StackBlitz project with the bug:

https://stackblitz.com/edit/react-ts-awwhac?file=App.tsx
