### ISSUE TITLE
Dependencies: Could not resolve dependency error

### ISSUE THREAD

**Issue by astefano** [f5/unovis#77]
Hello,

I wanted to experiment locally with unovis so as a starter, i've told myself i could download from stackblitz one of the gallery (angular) projects but when i run `npm install` i get:

```
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: set3nr--run@0.0.0
npm ERR! Found: @angular/common@15.0.3
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"15.0.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^12.0.3" from @unovis/angular@1.0.0
npm ERR! node_modules/@unovis/angular
npm ERR!   @unovis/angular@"1.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

when i try, in turn, either `--force` or `--legacy-peer-deps`, `ng serve` gives:

```
An unhandled exception occurred: require() of ES Module /Downloads/set3nr--run/node_modules/@angular/compiler/fesm2015/compiler.mjs not supported.
Instead change the require of /Downloads/set3nr--run/node_modules/@angular/compiler/fesm2015/compiler.mjs to a dynamic import() which is available in all CommonJS modules.
```

I'm on a Mac M1, and my node version is 19 but downgrading to 16 for instance doesn't help (i get the same errors).
I'm puzzled how come stackblitz can compile and run the project while locally i get these errors. I didn't figure it out how to use the dynamic import, so i was wondering if you might have a suggestion. Btw, the same error with `require` i see at https://npm.runkit.com/%40unovis%2Fangular.

Thank you!

**Comment by rokotyan** [comment]
@astefano Thanks for the detailed report!

We're using StackBlitz's official Angular template, and it's a bit of a mystery why it's working online and doesn't work locally. 

I would recommend you to simply create a new Angular project with `ng`, it's a fairly quick and simple procedure: https://angular.io/cli#basic-workflow

**Comment by rokotyan** [comment]
@astefano You'll probably need to use the latest beta version `1.0.1-beta.5`, because version `1.0.0` has some [errors](https://github.com/f5/unovis/issues/79).

**Comment by astefano** [comment]
Thank you for your feedback, i appreciate it!
