### ISSUE TITLE
Component | Graph: nodeFill doesn't accept CSS variables or custom SVG defs

### ISSUE THREAD

**Issue by reb-dev** [f5/unovis#80]
@rokotyan I noticed that unlike our other components, Graph doesn't support CSS variables or custom SVG defs for the node color. When providing either to `nodeFill` it fails with the following console error:

![Screen Shot 2022-12-20 at 2 08 15 PM](https://user-images.githubusercontent.com/52078477/208776198-01bd7425-0376-4c5a-bfbe-40198bd10433.png)

Is this by design or should we fix it?

**Comment by reb-dev** [comment]
For more context here is a side-by-side comparison w/ Area where custom color works:
![Screen Shot 2022-12-20 at 2 16 28 PM](https://user-images.githubusercontent.com/52078477/208778387-bddb9117-279d-4d85-bacb-37104cf0019e.png)

**Comment by rokotyan** [comment]
@reb-dev I think we should fix it. 

The `isStringCSSVariable` function can be helpful here (here is an [example](https://github.com/f5/unovis/blob/555e78dab536a89224713cf3a3ff4ee4f5565ca1/packages/ts/src/components/xy-labels/modules/label.ts#L65)) but it won't work with gradients. I feel like we need to come up with a new unified approach for handling cases like this in the library.
