### ISSUE TITLE
Next.js: Cannot read properties of undefined (reading 'baseVal')

### ISSUE THREAD

**Issue by asterikx** [f5/unovis#92]
When I deploy [Dagre Layout Graph](https://unovis.dev/gallery/view?collection=Networks%20and%20Flows&title=Dagre%20Layout%20Graph) in a Next.js application, I get the following error during the initial render:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'baseVal')
    at SVGGElement.defaultExtent (zoom.js?287e:25:1)
    at new Gesture (zoom.js?287e:186:1)
    at gesture (zoom.js?287e:178:1)
    at SVGGElement.eval (zoom.js?287e:92:1)
    at Selection.__WEBPACK_DEFAULT_EXPORT__ [as each] (each.js?664a:5:1)
    at zoom.transform (zoom.js?287e:91:1)
    at Selection.__WEBPACK_DEFAULT_EXPORT__ [as call] (call.js?2436:4:1)
    at Graph._fit (index.js?4995:278:1)
    at eval (index.js?4995:121:1)
```

Any idea how to fix or work around the error?

**Comment by rokotyan** [comment]
@asterikx Can you please create a sample [StackBlitz](https://stackblitz.com/) project reproducing the error? We've not tested the library with Next.js yet so it's a good opportunity for us to finally do it

**Comment by asterikx** [comment]
@rokotyan  Ah! I just figured out what causes the error: React Strict Mode. You can try toggling `reactStrictMode` in `next.config.js`.

**Comment by rokotyan** [comment]
Thanks @asterikx! We'll look into it

**Comment by rokotyan** [comment]
@asterikx The problem will be fixed in the `1.0.2` release, and you can already use version `1.0.2-beta.3` which contains the fix. Just set it in your `package.json`:
```
"@unovis/react": "1.0.2-beta.3",
"@unovis/ts": "1.0.2-beta.3",
```

**Comment by rokotyan** [comment]
@asterikx Version `1.0.2` has been released! Closing the issue.

**Comment by asterikx** [comment]
Thanks! 🎉
